import React, { useState } from 'react';
import { useQuery } from 'react-query';
import { hrService } from '../../services/api/hrService';
import { useAuth } from '../../contexts/AuthContext';
import './StaffPayroll.css';

const StaffPayroll = () => {
  const { user } = useAuth();
  const currentDate = new Date();
  const [selectedMonth, setSelectedMonth] = useState(currentDate.getMonth() + 1);
  const [selectedYear, setSelectedYear] = useState(currentDate.getFullYear());

  const { data: staffProfile } = useQuery('my-staff-profile', () => hrService.getMyStaffProfile(), {
    enabled: !!user?.id,
    refetchOnWindowFocus: false,
  });

  const { data: payrollData, isLoading } = useQuery(
    ['staff-payroll', staffProfile?.data?.id, selectedMonth, selectedYear],
    () =>
      hrService.getPayroll({
        month: selectedMonth,
        year: selectedYear,
      }),
    {
      enabled: !!staffProfile?.data?.id,
      refetchOnWindowFocus: false,
    }
  );

  const payrollRecords = payrollData?.data || [];

  // Filter payroll for current staff member
  const myPayroll = payrollRecords.filter(
    (record: any) => record.staff_id === staffProfile?.data?.id
  );

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'paid':
        return <span className="status-badge paid">Paid</span>;
      case 'generated':
        return <span className="status-badge generated">Generated</span>;
      case 'not_generated':
      default:
        return <span className="status-badge not-generated">Not Generated</span>;
    }
  };

  if (isLoading) {
    return <div className="loading">Loading payroll information...</div>;
  }

  return (
    <div className="staff-payroll-page">
      <div className="page-header">
        <h1>My Payroll</h1>
        <div className="filters">
          <div className="filter-group">
            <label>Month:</label>
            <select
              value={selectedMonth}
              onChange={(e) => setSelectedMonth(Number(e.target.value))}
            >
              {Array.from({ length: 12 }, (_, i) => i + 1).map((month) => (
                <option key={month} value={month}>
                  {new Date(2000, month - 1).toLocaleString('default', { month: 'long' })}
                </option>
              ))}
            </select>
          </div>
          <div className="filter-group">
            <label>Year:</label>
            <select
              value={selectedYear}
              onChange={(e) => setSelectedYear(Number(e.target.value))}
            >
              {Array.from({ length: 5 }, (_, i) => currentDate.getFullYear() - 2 + i).map((year) => (
                <option key={year} value={year}>
                  {year}
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      <div className="payroll-content">
        {myPayroll.length === 0 ? (
          <div className="empty-state">
            <p>No payroll records found for the selected period.</p>
            <p className="empty-state-subtitle">
              Payroll records are generated by the administrator. Please contact HR if you have any questions.
            </p>
          </div>
        ) : (
          <div className="payroll-list">
            {myPayroll.map((record: any) => (
              <div key={record.id} className="payroll-card">
                <div className="payroll-header">
                  <div>
                    <h3>
                      Payroll for {new Date(record.year, record.month - 1).toLocaleString('default', {
                        month: 'long',
                        year: 'numeric',
                      })}
                    </h3>
                    <p className="payroll-id">Payroll ID: #{record.id}</p>
                  </div>
                  {getStatusBadge(record.status)}
                </div>
                <div className="payroll-body">
                  <div className="payroll-details">
                    <div className="detail-row">
                      <span className="detail-label">Basic Salary:</span>
                      <span className="detail-value">₹{parseFloat(record.basic_salary || 0).toLocaleString()}</span>
                    </div>
                    {record.allowances && parseFloat(record.allowances) > 0 && (
                      <div className="detail-row">
                        <span className="detail-label">Allowances:</span>
                        <span className="detail-value">₹{parseFloat(record.allowances).toLocaleString()}</span>
                      </div>
                    )}
                    {record.deductions && parseFloat(record.deductions) > 0 && (
                      <div className="detail-row">
                        <span className="detail-label">Deductions:</span>
                        <span className="detail-value deduction">-₹{parseFloat(record.deductions).toLocaleString()}</span>
                      </div>
                    )}
                    <div className="detail-row total">
                      <span className="detail-label">Net Salary:</span>
                      <span className="detail-value">
                        ₹{parseFloat(record.net_salary || record.basic_salary || 0).toLocaleString()}
                      </span>
                    </div>
                    {record.payment_date && (
                      <div className="detail-row">
                        <span className="detail-label">Payment Date:</span>
                        <span className="detail-value">
                          {new Date(record.payment_date).toLocaleDateString()}
                        </span>
                      </div>
                    )}
                    {record.note && (
                      <div className="detail-row">
                        <span className="detail-label">Note:</span>
                        <span className="detail-value">{record.note}</span>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default StaffPayroll;

