-- ============================================================================
-- SchoolWizard Database - Consolidated SQL File
-- This file was automatically generated by combining multiple migration files
-- ============================================================================
-- IMPORTANT: Run files in order: 01, 02, 03, 04, 05
-- ============================================================================

USE schoolwizard;

-- ============================================================================
-- Source: 002_academics_tables.sql
-- ============================================================================

-- Academics Module Tables

-- Subjects Table
CREATE TABLE IF NOT EXISTS subjects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(50),
    type ENUM('theory', 'practical') DEFAULT 'theory',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_name (name),
    INDEX idx_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Subject Groups Table
CREATE TABLE IF NOT EXISTS subject_groups (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    class_id INT NOT NULL,
    section_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
    FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE CASCADE,
    INDEX idx_class_section (class_id, section_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Subject Group Subjects (Many-to-Many)
CREATE TABLE IF NOT EXISTS subject_group_subjects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    subject_group_id INT NOT NULL,
    subject_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (subject_group_id) REFERENCES subject_groups(id) ON DELETE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE,
    UNIQUE KEY unique_subject_group_subject (subject_group_id, subject_id),
    INDEX idx_subject_group (subject_group_id),
    INDEX idx_subject (subject_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Class Teachers (Assign teachers to class-sections)
CREATE TABLE IF NOT EXISTS class_teachers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    class_id INT NOT NULL,
    section_id INT NOT NULL,
    teacher_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
    FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE CASCADE,
    FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE KEY unique_class_section_teacher (class_id, section_id, teacher_id),
    INDEX idx_class_section (class_id, section_id),
    INDEX idx_teacher (teacher_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Class Timetable
CREATE TABLE IF NOT EXISTS class_timetable (
    id INT AUTO_INCREMENT PRIMARY KEY,
    class_id INT NOT NULL,
    section_id INT NOT NULL,
    subject_group_id INT NOT NULL,
    subject_id INT NOT NULL,
    teacher_id INT,
    day_of_week ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday') NOT NULL,
    time_from TIME NOT NULL,
    time_to TIME NOT NULL,
    room_no VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
    FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE CASCADE,
    FOREIGN KEY (subject_group_id) REFERENCES subject_groups(id) ON DELETE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE,
    FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_class_section (class_id, section_id),
    INDEX idx_day (day_of_week)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;




-- ============================================================================
-- Source: 003_add_missing_columns_only.sql
-- ============================================================================

-- Add only the columns that are actually missing
-- This script checks if each column exists before adding it
-- Run this in phpMyAdmin SQL tab

USE schoolwizard;

-- Function to add column only if it doesn't exist
-- Note: MySQL doesn't support IF NOT EXISTS in ALTER TABLE directly
-- So we'll use a stored procedure approach or just run them individually

-- Since father_photo already exists (you got the duplicate error), skip it
-- Just run the ones that don't exist yet

-- Add mother_photo (if missing)
ALTER TABLE students ADD COLUMN mother_photo VARCHAR(255) AFTER mother_email;

-- Add guardian_photo (if missing)
ALTER TABLE students ADD COLUMN guardian_photo VARCHAR(255) AFTER guardian_email;

-- Add transport_route_id (if missing)
ALTER TABLE students ADD COLUMN transport_route_id INT AFTER permanent_address;

-- Add hostel_id (if missing)
ALTER TABLE students ADD COLUMN hostel_id INT AFTER transport_route_id;

-- Add hostel_room_id (if missing)
ALTER TABLE students ADD COLUMN hostel_room_id INT AFTER hostel_id;

-- After running, verify the count
-- Should have 49 columns total (including id, created_at, updated_at)
SELECT COUNT(*) as total_columns FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'schoolwizard' AND TABLE_NAME = 'students';




-- ============================================================================
-- Source: 003_check_and_add_columns.sql
-- ============================================================================

-- Script to check which columns exist and add only the missing ones
-- Run this in phpMyAdmin SQL tab

USE schoolwizard;

-- Check current columns
SELECT COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'schoolwizard'
AND TABLE_NAME = 'students'
ORDER BY ORDINAL_POSITION;

-- Now add only the missing columns
-- Run these one by one and skip any that give "Duplicate column name" errors

-- Try to add father_photo (skip if error)
ALTER TABLE students ADD COLUMN father_photo VARCHAR(255) AFTER father_email;

-- Try to add mother_photo (skip if error)
ALTER TABLE students ADD COLUMN mother_photo VARCHAR(255) AFTER mother_email;

-- Try to add guardian_photo (skip if error)
ALTER TABLE students ADD COLUMN guardian_photo VARCHAR(255) AFTER guardian_email;

-- Try to add transport_route_id (skip if error)
ALTER TABLE students ADD COLUMN transport_route_id INT AFTER permanent_address;

-- Try to add hostel_id (skip if error)
ALTER TABLE students ADD COLUMN hostel_id INT AFTER transport_route_id;

-- Try to add hostel_room_id (skip if error)
ALTER TABLE students ADD COLUMN hostel_room_id INT AFTER hostel_id;

-- Verify final structure
SELECT COUNT(*) as total_columns FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'schoolwizard' AND TABLE_NAME = 'students';




-- ============================================================================
-- Source: 003_get_exact_table_structure.sql
-- ============================================================================

-- Get the exact structure of the students table
-- Run this to see all columns in order

USE schoolwizard;

-- Get all columns in the exact order they appear in the table
SELECT 
    ORDINAL_POSITION as position,
    COLUMN_NAME as column_name,
    DATA_TYPE as data_type,
    IS_NULLABLE as nullable
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'schoolwizard'
AND TABLE_NAME = 'students'
ORDER BY ORDINAL_POSITION;

-- Count total columns (should be 49 including id, created_at, updated_at)
SELECT COUNT(*) as total_columns 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'schoolwizard' 
AND TABLE_NAME = 'students';

-- List columns that should be in INSERT (excluding id, created_at, updated_at, disable_reason_id, disable_date)
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'schoolwizard'
AND TABLE_NAME = 'students'
AND COLUMN_NAME NOT IN ('id', 'created_at', 'updated_at', 'disable_reason_id', 'disable_date')
ORDER BY ORDINAL_POSITION;




-- ============================================================================
-- Source: 003_students_tables.sql
-- ============================================================================

-- Student Information Module Tables

-- Student Categories
CREATE TABLE IF NOT EXISTS student_categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Student Houses
CREATE TABLE IF NOT EXISTS student_houses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Disable Reasons
CREATE TABLE IF NOT EXISTS disable_reasons (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Students Table
-- Note: This table includes all columns. If you get column count errors, 
-- make sure this migration has been run: mysql -u root schoolwizard < database/migrations/003_students_tables.sql
CREATE TABLE IF NOT EXISTS students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    admission_no VARCHAR(50) NOT NULL UNIQUE,
    roll_no VARCHAR(50),
    user_id INT,
    class_id INT NOT NULL,
    section_id INT NOT NULL,
    session_id INT NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255),
    gender ENUM('male', 'female', 'other') NOT NULL,
    date_of_birth DATE NOT NULL,
    category_id INT,
    religion VARCHAR(100),
    caste VARCHAR(100),
    student_mobile VARCHAR(20),
    email VARCHAR(255),
    admission_date DATE NOT NULL,
    photo VARCHAR(255),
    blood_group VARCHAR(10),
    house_id INT,
    height VARCHAR(20),
    weight VARCHAR(20),
    as_on_date DATE,
    sibling_id INT,
    -- Father Details
    father_name VARCHAR(255),
    father_occupation VARCHAR(255),
    father_phone VARCHAR(20),
    father_email VARCHAR(255),
    father_photo VARCHAR(255),
    -- Mother Details
    mother_name VARCHAR(255),
    mother_occupation VARCHAR(255),
    mother_phone VARCHAR(20),
    mother_email VARCHAR(255),
    mother_photo VARCHAR(255),
    -- Guardian Details
    guardian_name VARCHAR(255),
    guardian_relation VARCHAR(100),
    guardian_occupation VARCHAR(255),
    guardian_phone VARCHAR(20),
    guardian_email VARCHAR(255),
    guardian_photo VARCHAR(255),
    -- Address Details
    current_address TEXT,
    permanent_address TEXT,
    -- Transport
    transport_route_id INT,
    -- Hostel
    hostel_id INT,
    hostel_room_id INT,
    -- RTE
    is_rte TINYINT(1) DEFAULT 0,
    rte_details TEXT,
    -- Status
    is_active TINYINT(1) DEFAULT 1,
    disable_reason_id INT,
    disable_date DATE,
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE RESTRICT,
    FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE RESTRICT,
    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE RESTRICT,
    FOREIGN KEY (category_id) REFERENCES student_categories(id) ON DELETE SET NULL,
    FOREIGN KEY (house_id) REFERENCES student_houses(id) ON DELETE SET NULL,
    FOREIGN KEY (disable_reason_id) REFERENCES disable_reasons(id) ON DELETE SET NULL,
    INDEX idx_admission_no (admission_no),
    INDEX idx_class_section (class_id, section_id),
    INDEX idx_session (session_id),
    INDEX idx_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Student Documents
CREATE TABLE IF NOT EXISTS student_documents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    document_name VARCHAR(255) NOT NULL,
    document_path VARCHAR(500) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    INDEX idx_student (student_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Online Admissions (Pending)
CREATE TABLE IF NOT EXISTS online_admissions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    admission_no VARCHAR(50),
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255),
    gender ENUM('male', 'female', 'other') NOT NULL,
    date_of_birth DATE NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(20),
    class_id INT,
    number_of_child INT DEFAULT 1,
    -- Parent Details
    father_name VARCHAR(255),
    father_phone VARCHAR(20),
    mother_name VARCHAR(255),
    mother_phone VARCHAR(20),
    guardian_name VARCHAR(255),
    guardian_phone VARCHAR(20),
    -- Address
    address TEXT,
    -- Status
    status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE SET NULL,
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



-- ============================================================================
-- Source: 003_students_tables_ALTER.sql
-- ============================================================================

-- ALTER script to add missing columns to students table if they don't exist
-- Run this if you get "Column count doesn't match" errors
-- Usage: mysql -u root schoolwizard < database/migrations/003_students_tables_ALTER.sql

USE schoolwizard;

-- Add missing columns if they don't exist
ALTER TABLE students 
ADD COLUMN IF NOT EXISTS father_photo VARCHAR(255) AFTER father_email,
ADD COLUMN IF NOT EXISTS mother_photo VARCHAR(255) AFTER mother_email,
ADD COLUMN IF NOT EXISTS guardian_photo VARCHAR(255) AFTER guardian_email,
ADD COLUMN IF NOT EXISTS transport_route_id INT AFTER permanent_address,
ADD COLUMN IF NOT EXISTS hostel_id INT AFTER transport_route_id,
ADD COLUMN IF NOT EXISTS hostel_room_id INT AFTER hostel_id;

-- Note: If the above doesn't work (MySQL version < 8.0.19), use this instead:
-- Check each column and add if missing manually in phpMyAdmin or MySQL client




-- ============================================================================
-- Source: 003_students_tables_ALTER_SAFE.sql
-- ============================================================================

-- Safe ALTER script to add missing columns to students table
-- This will NOT delete any data
-- Run this in phpMyAdmin SQL tab or MySQL client

USE schoolwizard;

-- Disable foreign key checks temporarily (MySQL will re-enable automatically)
SET FOREIGN_KEY_CHECKS = 0;

-- Add missing columns one by one
-- If a column already exists, you'll get an error - that's okay, just continue

-- Check and add father_photo
SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_SCHEMA = 'schoolwizard' 
  AND TABLE_NAME = 'students' 
  AND COLUMN_NAME = 'father_photo');
SET @sql = IF(@col_exists = 0, 
  'ALTER TABLE students ADD COLUMN father_photo VARCHAR(255) AFTER father_email', 
  'SELECT "Column father_photo already exists" AS message');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Check and add mother_photo
SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_SCHEMA = 'schoolwizard' 
  AND TABLE_NAME = 'students' 
  AND COLUMN_NAME = 'mother_photo');
SET @sql = IF(@col_exists = 0, 
  'ALTER TABLE students ADD COLUMN mother_photo VARCHAR(255) AFTER mother_email', 
  'SELECT "Column mother_photo already exists" AS message');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Check and add guardian_photo
SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_SCHEMA = 'schoolwizard' 
  AND TABLE_NAME = 'students' 
  AND COLUMN_NAME = 'guardian_photo');
SET @sql = IF(@col_exists = 0, 
  'ALTER TABLE students ADD COLUMN guardian_photo VARCHAR(255) AFTER guardian_email', 
  'SELECT "Column guardian_photo already exists" AS message');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Check and add transport_route_id
SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_SCHEMA = 'schoolwizard' 
  AND TABLE_NAME = 'students' 
  AND COLUMN_NAME = 'transport_route_id');
SET @sql = IF(@col_exists = 0, 
  'ALTER TABLE students ADD COLUMN transport_route_id INT AFTER permanent_address', 
  'SELECT "Column transport_route_id already exists" AS message');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Check and add hostel_id
SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_SCHEMA = 'schoolwizard' 
  AND TABLE_NAME = 'students' 
  AND COLUMN_NAME = 'hostel_id');
SET @sql = IF(@col_exists = 0, 
  'ALTER TABLE students ADD COLUMN hostel_id INT AFTER transport_route_id', 
  'SELECT "Column hostel_id already exists" AS message');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Check and add hostel_room_id
SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_SCHEMA = 'schoolwizard' 
  AND TABLE_NAME = 'students' 
  AND COLUMN_NAME = 'hostel_room_id');
SET @sql = IF(@col_exists = 0, 
  'ALTER TABLE students ADD COLUMN hostel_room_id INT AFTER hostel_id', 
  'SELECT "Column hostel_room_id already exists" AS message');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;

-- Verify the table structure
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'schoolwizard'
AND TABLE_NAME = 'students'
ORDER BY ORDINAL_POSITION;




-- ============================================================================
-- Source: 003_students_tables_ALTER_SIMPLE.sql
-- ============================================================================

-- Simple ALTER script to add missing columns
-- Run this in phpMyAdmin SQL tab
-- If you get "Duplicate column name" errors, that means the column already exists - that's fine!

USE schoolwizard;

-- Add missing columns (ignore errors if they already exist)
ALTER TABLE students ADD COLUMN father_photo VARCHAR(255) AFTER father_email;
ALTER TABLE students ADD COLUMN mother_photo VARCHAR(255) AFTER mother_email;
ALTER TABLE students ADD COLUMN guardian_photo VARCHAR(255) AFTER guardian_email;
ALTER TABLE students ADD COLUMN transport_route_id INT AFTER permanent_address;
ALTER TABLE students ADD COLUMN hostel_id INT AFTER transport_route_id;
ALTER TABLE students ADD COLUMN hostel_room_id INT AFTER hostel_id;

-- Verify: This should show 49 columns total (including id, created_at, updated_at)
SELECT COUNT(*) as total_columns FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'schoolwizard' AND TABLE_NAME = 'students';




-- ============================================================================
-- Source: 003_verify_table_structure.sql
-- ============================================================================

-- Script to verify the students table structure
-- Run this first to see what columns you have

USE schoolwizard;

-- List all columns in the students table
SELECT 
    ORDINAL_POSITION as position,
    COLUMN_NAME as column_name,
    DATA_TYPE as data_type,
    IS_NULLABLE as nullable,
    COLUMN_DEFAULT as default_value
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'schoolwizard'
AND TABLE_NAME = 'students'
ORDER BY ORDINAL_POSITION;

-- Count total columns
SELECT COUNT(*) as total_columns 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'schoolwizard' 
AND TABLE_NAME = 'students';

-- Check for specific missing columns
SELECT 
    CASE WHEN EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = 'schoolwizard' 
        AND TABLE_NAME = 'students' 
        AND COLUMN_NAME = 'father_photo'
    ) THEN 'EXISTS' ELSE 'MISSING' END as father_photo,
    CASE WHEN EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = 'schoolwizard' 
        AND TABLE_NAME = 'students' 
        AND COLUMN_NAME = 'mother_photo'
    ) THEN 'EXISTS' ELSE 'MISSING' END as mother_photo,
    CASE WHEN EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = 'schoolwizard' 
        AND TABLE_NAME = 'students' 
        AND COLUMN_NAME = 'guardian_photo'
    ) THEN 'EXISTS' ELSE 'MISSING' END as guardian_photo,
    CASE WHEN EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = 'schoolwizard' 
        AND TABLE_NAME = 'students' 
        AND COLUMN_NAME = 'transport_route_id'
    ) THEN 'EXISTS' ELSE 'MISSING' END as transport_route_id,
    CASE WHEN EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = 'schoolwizard' 
        AND TABLE_NAME = 'students' 
        AND COLUMN_NAME = 'hostel_id'
    ) THEN 'EXISTS' ELSE 'MISSING' END as hostel_id,
    CASE WHEN EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = 'schoolwizard' 
        AND TABLE_NAME = 'students' 
        AND COLUMN_NAME = 'hostel_room_id'
    ) THEN 'EXISTS' ELSE 'MISSING' END as hostel_room_id;




-- ============================================================================
-- Source: 010_add_admit_card_fields.sql
-- ============================================================================

-- Add missing columns to admit_card_templates table
USE schoolwizard;

ALTER TABLE admit_card_templates
ADD COLUMN IF NOT EXISTS heading VARCHAR(255) AFTER name,
ADD COLUMN IF NOT EXISTS title VARCHAR(255) AFTER heading,
ADD COLUMN IF NOT EXISTS exam_name VARCHAR(255) AFTER title;




-- ============================================================================
-- Source: 012_fix_student_photo_column.sql
-- ============================================================================

-- Fix student photo column to support base64 images
-- Base64 encoded images are much longer than 255 characters
-- This migration changes the photo column from VARCHAR(255) to LONGTEXT

USE schoolwizard;

-- Change photo column to LONGTEXT to support full base64 image data
ALTER TABLE students MODIFY COLUMN photo LONGTEXT;

-- Also update parent photo columns if they exist
ALTER TABLE students MODIFY COLUMN father_photo LONGTEXT;
ALTER TABLE students MODIFY COLUMN mother_photo LONGTEXT;
ALTER TABLE students MODIFY COLUMN guardian_photo LONGTEXT;

-- Verify the change
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'schoolwizard' 
AND TABLE_NAME = 'students' 
AND COLUMN_NAME LIKE '%photo%';




