-- ============================================================================
-- SchoolWizard Database - Consolidated SQL File
-- This file was automatically generated by combining multiple migration files
-- ============================================================================
-- IMPORTANT: Run files in order: 01, 02, 03, 04, 05
-- ============================================================================

USE schoolwizard;

-- ============================================================================
-- Source: 024_front_cms_tables.sql
-- ============================================================================

USE schoolwizard;

-- Front CMS Pages Table (created first as it's referenced by menu_items)
CREATE TABLE IF NOT EXISTS front_cms_pages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    page_title VARCHAR(255) NOT NULL,
    page_type ENUM('standard', 'event', 'news', 'gallery') DEFAULT 'standard',
    description TEXT,
    meta_title VARCHAR(255),
    meta_keyword VARCHAR(500),
    meta_description TEXT,
    sidebar_enabled BOOLEAN DEFAULT TRUE,
    featured_image VARCHAR(500),
    slug VARCHAR(255) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_page_type (page_type),
    INDEX idx_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Front CMS Menus Table
CREATE TABLE IF NOT EXISTS front_cms_menus (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Front CMS Menu Items Table
CREATE TABLE IF NOT EXISTS front_cms_menu_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    menu_id INT NOT NULL,
    parent_id INT NULL,
    menu_item VARCHAR(255) NOT NULL,
    external_url VARCHAR(500),
    open_in_new_tab BOOLEAN DEFAULT FALSE,
    page_id INT NULL,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (menu_id) REFERENCES front_cms_menus(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_id) REFERENCES front_cms_menu_items(id) ON DELETE CASCADE,
    FOREIGN KEY (page_id) REFERENCES front_cms_pages(id) ON DELETE SET NULL,
    INDEX idx_menu_id (menu_id),
    INDEX idx_parent_id (parent_id),
    INDEX idx_sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Front CMS Events Table (Public Events)
CREATE TABLE IF NOT EXISTS front_cms_events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    event_title VARCHAR(255) NOT NULL,
    event_venue VARCHAR(255),
    event_start_date DATE NOT NULL,
    event_end_date DATE,
    description TEXT,
    meta_title VARCHAR(255),
    meta_keyword VARCHAR(500),
    meta_description TEXT,
    sidebar_enabled BOOLEAN DEFAULT TRUE,
    featured_image VARCHAR(500),
    slug VARCHAR(255) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_event_start_date (event_start_date),
    INDEX idx_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Front CMS Galleries Table
CREATE TABLE IF NOT EXISTS front_cms_galleries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    gallery_title VARCHAR(255) NOT NULL,
    description TEXT,
    meta_title VARCHAR(255),
    meta_keyword VARCHAR(500),
    meta_description TEXT,
    sidebar_enabled BOOLEAN DEFAULT TRUE,
    featured_image VARCHAR(500),
    slug VARCHAR(255) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Front CMS Gallery Images Table
CREATE TABLE IF NOT EXISTS front_cms_gallery_images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    gallery_id INT NOT NULL,
    image_path VARCHAR(500) NOT NULL,
    image_title VARCHAR(255),
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (gallery_id) REFERENCES front_cms_galleries(id) ON DELETE CASCADE,
    INDEX idx_gallery_id (gallery_id),
    INDEX idx_sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Front CMS News Table
CREATE TABLE IF NOT EXISTS front_cms_news (
    id INT AUTO_INCREMENT PRIMARY KEY,
    news_title VARCHAR(255) NOT NULL,
    news_date DATE NOT NULL,
    description TEXT,
    meta_title VARCHAR(255),
    meta_keyword VARCHAR(500),
    meta_description TEXT,
    sidebar_enabled BOOLEAN DEFAULT TRUE,
    featured_image VARCHAR(500),
    slug VARCHAR(255) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_news_date (news_date),
    INDEX idx_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Front CMS Media Table
CREATE TABLE IF NOT EXISTS front_cms_media (
    id INT AUTO_INCREMENT PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_type ENUM('image', 'document', 'video') NOT NULL,
    file_size INT,
    mime_type VARCHAR(100),
    youtube_url VARCHAR(500),
    alt_text VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_file_type (file_type),
    INDEX idx_file_name (file_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Front CMS Banner Images Table
CREATE TABLE IF NOT EXISTS front_cms_banner_images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image_path VARCHAR(500) NOT NULL,
    image_title VARCHAR(255),
    image_link VARCHAR(500),
    sort_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_sort_order (sort_order),
    INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;




-- ============================================================================
-- Source: 030_front_cms_website_settings.sql
-- ============================================================================

-- Front CMS Website Settings Table
CREATE TABLE IF NOT EXISTS front_cms_website_settings (
  id INT PRIMARY KEY AUTO_INCREMENT,
  website_logo VARCHAR(255) NULL,
  school_name VARCHAR(255) NOT NULL DEFAULT 'School Name',
  tag_line VARCHAR(255) NULL,
  tag_line_visible BOOLEAN DEFAULT TRUE,
  contact_email VARCHAR(255) NULL,
  contact_phone VARCHAR(50) NULL,
  facebook_url VARCHAR(255) NULL,
  facebook_enabled BOOLEAN DEFAULT FALSE,
  twitter_url VARCHAR(255) NULL,
  twitter_enabled BOOLEAN DEFAULT FALSE,
  youtube_url VARCHAR(255) NULL,
  youtube_enabled BOOLEAN DEFAULT FALSE,
  instagram_url VARCHAR(255) NULL,
  instagram_enabled BOOLEAN DEFAULT FALSE,
  linkedin_url VARCHAR(255) NULL,
  linkedin_enabled BOOLEAN DEFAULT FALSE,
  whatsapp_url VARCHAR(255) NULL,
  whatsapp_enabled BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_settings (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Front CMS Banner Carousel Table
CREATE TABLE IF NOT EXISTS front_cms_banners (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  image_path VARCHAR(255) NOT NULL,
  button_text VARCHAR(100) NULL,
  button_url VARCHAR(255) NULL,
  sort_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_sort_order (sort_order),
  INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default settings (only if table is empty)
INSERT INTO front_cms_website_settings (school_name, tag_line, tag_line_visible, contact_email, contact_phone)
SELECT 'School Name', 'A School with a Difference', TRUE, 'info@schoolname.edu', '+91 1234567890'
WHERE NOT EXISTS (SELECT 1 FROM front_cms_website_settings);




-- ============================================================================
-- Source: 031_about_us_page_content.sql
-- ============================================================================

-- About Us Page Content Tables

-- Mission & Vision Table
CREATE TABLE IF NOT EXISTS front_cms_about_us_mission_vision (
  id INT PRIMARY KEY AUTO_INCREMENT,
  mission_content TEXT NOT NULL,
  vision_content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_mission_vision (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Counter/Stats Table
CREATE TABLE IF NOT EXISTS front_cms_about_us_counters (
  id INT PRIMARY KEY AUTO_INCREMENT,
  counter_number VARCHAR(50) NOT NULL,
  counter_label VARCHAR(255) NOT NULL,
  sort_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_sort_order (sort_order),
  INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- History Content Table
CREATE TABLE IF NOT EXISTS front_cms_about_us_history (
  id INT PRIMARY KEY AUTO_INCREMENT,
  history_content TEXT NOT NULL,
  history_image VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_history (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Core Values Table
CREATE TABLE IF NOT EXISTS front_cms_about_us_values (
  id INT PRIMARY KEY AUTO_INCREMENT,
  icon_class VARCHAR(100) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  sort_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_sort_order (sort_order),
  INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Achievements Table
CREATE TABLE IF NOT EXISTS front_cms_about_us_achievements (
  id INT PRIMARY KEY AUTO_INCREMENT,
  achievement_year VARCHAR(20) NOT NULL,
  achievement_title VARCHAR(255) NOT NULL,
  achievement_description TEXT NOT NULL,
  sort_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_sort_order (sort_order),
  INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Leadership Table
CREATE TABLE IF NOT EXISTS front_cms_about_us_leadership (
  id INT PRIMARY KEY AUTO_INCREMENT,
  leader_name VARCHAR(255) NOT NULL,
  leader_role VARCHAR(255) NOT NULL,
  leader_bio TEXT NOT NULL,
  leader_image VARCHAR(255) NULL,
  sort_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_sort_order (sort_order),
  INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default Mission & Vision
INSERT INTO front_cms_about_us_mission_vision (mission_content, vision_content)
VALUES (
  'To provide a holistic education that nurtures the intellectual, physical, emotional, and social development of every student. We are committed to creating a learning environment that inspires curiosity, fosters creativity, and prepares students to become responsible global citizens.',
  'To be a leading educational institution recognized for academic excellence, innovative teaching methods, and the development of well-rounded individuals who contribute positively to society. We envision a school where every student realizes their full potential.'
)
ON DUPLICATE KEY UPDATE mission_content = mission_content;

-- Insert default History
INSERT INTO front_cms_about_us_history (history_content, history_image)
VALUES (
  'Founded in 1974, our school has been a beacon of educational excellence for over five decades. What started as a small institution with a vision to provide quality education has grown into one of the most respected schools in the region.\n\nOver the years, we have continuously evolved to meet the changing needs of education while maintaining our core values of excellence, integrity, and community. Our commitment to providing a well-rounded education has helped thousands of students achieve their dreams and make meaningful contributions to society.\n\nToday, we stand proud of our legacy while looking forward to an even brighter future. We continue to invest in modern facilities, innovative teaching methods, and comprehensive programs that prepare our students for the challenges and opportunities of the 21st century.',
  NULL
)
ON DUPLICATE KEY UPDATE history_content = history_content;




-- ============================================================================
-- Source: 032_admission_management.sql
-- ============================================================================

-- Admission Management Tables

-- Admission Inquiries Table (submissions from public website)
CREATE TABLE IF NOT EXISTS admission_inquiries (
  id INT PRIMARY KEY AUTO_INCREMENT,
  student_name VARCHAR(255) NOT NULL,
  parent_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  grade VARCHAR(50) NOT NULL,
  previous_school VARCHAR(255) NULL,
  address TEXT NOT NULL,
  message TEXT NULL,
  status ENUM('pending', 'contacted', 'approved', 'rejected') DEFAULT 'pending',
  notes TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_status (status),
  INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Important Dates Table
CREATE TABLE IF NOT EXISTS admission_important_dates (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  date_value DATE NOT NULL,
  description TEXT NULL,
  sort_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_sort_order (sort_order),
  INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Admission Contact Details Table
CREATE TABLE IF NOT EXISTS admission_contact_details (
  id INT PRIMARY KEY AUTO_INCREMENT,
  call_us_numbers TEXT NULL, -- JSON array of phone numbers
  email_us_addresses TEXT NULL, -- JSON array of email addresses
  visit_us_address TEXT NULL,
  office_hours TEXT NULL,
  important_dates_visible BOOLEAN DEFAULT TRUE,
  contact_details_visible BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_contact_details (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default contact details
INSERT INTO admission_contact_details (
  call_us_numbers,
  email_us_addresses,
  visit_us_address,
  office_hours,
  important_dates_visible,
  contact_details_visible
)
VALUES (
  '["+91 1234567890", "+91 9876543210"]',
  '["admissions@schoolname.edu", "info@schoolname.edu"]',
  'School Address, City\nState - PIN Code',
  'Monday - Friday: 9:00 AM - 5:00 PM\nSaturday: 9:00 AM - 1:00 PM',
  TRUE,
  TRUE
)
ON DUPLICATE KEY UPDATE call_us_numbers = call_us_numbers;

-- Contact Messages Table (submissions from public website contact form)
CREATE TABLE IF NOT EXISTS contact_messages (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NULL,
  subject VARCHAR(255) NULL,
  message TEXT NOT NULL,
  status ENUM('new', 'read', 'replied', 'archived') DEFAULT 'new',
  notes TEXT NULL,
  replied_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_status (status),
  INDEX idx_created_at (created_at),
  INDEX idx_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default important dates
INSERT INTO admission_important_dates (title, date_value, description, sort_order, is_active)
VALUES
  ('Application Start', '2025-01-01', 'Admission applications open for the new academic year', 1, TRUE),
  ('Last Date', '2025-03-31', 'Last date to submit admission applications', 2, TRUE),
  ('Assessment', '2025-04-15', 'Student assessment and interaction sessions (April 15-30, 2025)', 3, TRUE),
  ('Result Declaration', '2025-05-15', 'Admission results will be announced', 4, TRUE)
ON DUPLICATE KEY UPDATE title = title;




-- ============================================================================
-- Source: 033_gallery_management.sql
-- ============================================================================

-- Gallery Management Tables

-- Gallery Categories Table
CREATE TABLE IF NOT EXISTS gallery_categories (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  description TEXT NULL,
  sort_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_sort_order (sort_order),
  INDEX idx_is_active (is_active),
  UNIQUE KEY unique_category_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Gallery Images Table
CREATE TABLE IF NOT EXISTS gallery_images (
  id INT PRIMARY KEY AUTO_INCREMENT,
  category_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  image_path VARCHAR(500) NOT NULL,
  sort_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_category_id (category_id),
  INDEX idx_sort_order (sort_order),
  INDEX idx_is_active (is_active),
  FOREIGN KEY (category_id) REFERENCES gallery_categories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default categories
INSERT INTO gallery_categories (name, description, sort_order, is_active)
VALUES
  ('Events', 'School events and celebrations', 1, TRUE),
  ('Sports', 'Sports activities and competitions', 2, TRUE),
  ('Academics', 'Academic activities and achievements', 3, TRUE),
  ('Cultural', 'Cultural programs and performances', 4, TRUE)
ON DUPLICATE KEY UPDATE name = name;




-- ============================================================================
-- Source: 034_news_events_management.sql
-- ============================================================================

-- News and Events Management Tables

-- News Table
CREATE TABLE IF NOT EXISTS news_articles (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  excerpt TEXT NULL,
  content TEXT NOT NULL,
  category VARCHAR(100) NOT NULL DEFAULT 'general',
  featured_image VARCHAR(500) NULL,
  author VARCHAR(255) NULL,
  published_date DATE NOT NULL,
  is_featured BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  views_count INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_category (category),
  INDEX idx_published_date (published_date),
  INDEX idx_is_active (is_active),
  INDEX idx_is_featured (is_featured),
  INDEX idx_slug (slug),
  UNIQUE KEY unique_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Events Table
CREATE TABLE IF NOT EXISTS events (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR(100) NOT NULL DEFAULT 'general',
  event_date DATE NOT NULL,
  event_time TIME NULL,
  end_date DATE NULL,
  end_time TIME NULL,
  venue VARCHAR(255) NULL,
  featured_image VARCHAR(500) NULL,
  is_featured BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_category (category),
  INDEX idx_event_date (event_date),
  INDEX idx_is_active (is_active),
  INDEX idx_is_featured (is_featured),
  INDEX idx_slug (slug),
  UNIQUE KEY unique_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert sample news
INSERT INTO news_articles (title, slug, excerpt, content, category, author, published_date, is_featured, is_active)
VALUES
  ('Annual Science Fair 2024 - A Grand Success', 'annual-science-fair-2024', 'Students showcased innovative projects and experiments at our annual science fair, demonstrating creativity and scientific thinking.', 'Students showcased innovative projects and experiments at our annual science fair, demonstrating creativity and scientific thinking. The event featured over 50 projects covering various scientific disciplines including physics, chemistry, biology, and environmental science.', 'academic', 'School Admin', CURDATE(), TRUE, TRUE),
  ('Basketball Team Wins Regional Championship', 'basketball-team-wins-regional-championship', 'Our school basketball team emerged victorious in the regional championship, bringing home the trophy and pride to our institution.', 'Our school basketball team emerged victorious in the regional championship, bringing home the trophy and pride to our institution. The team displayed exceptional teamwork and determination throughout the tournament.', 'sports', 'Sports Department', DATE_SUB(CURDATE(), INTERVAL 5 DAY), FALSE, TRUE)
ON DUPLICATE KEY UPDATE title = title;

-- Insert sample events
INSERT INTO events (title, slug, description, category, event_date, event_time, venue, is_featured, is_active)
VALUES
  ('Annual Sports Day', 'annual-sports-day-2025', 'Join us for our annual sports day featuring exciting competitions, races, and team events. All students, parents, and staff are welcome.', 'Sports', DATE_ADD(CURDATE(), INTERVAL 20 DAY), '09:00:00', 'School Grounds', TRUE, TRUE),
  ('Science Exhibition', 'science-exhibition-2025', 'Students showcase innovative science projects and experiments. Open to all visitors interested in scientific exploration.', 'Academic', DATE_ADD(CURDATE(), INTERVAL 25 DAY), '10:00:00', 'School Auditorium', FALSE, TRUE)
ON DUPLICATE KEY UPDATE title = title;




